from collections import defaultdict

# Initialize state
farm_reward_times = defaultdict(lambda: [])
farm_skip_times = defaultdict(lambda: [])
prove_method = defaultdict(lambda: {})
farmer_ip = "127.0.0.1"
farmer_port = 8016
front_end_ip = "127.0.0.1"
front_end_port = 8181
plot_time_seconds = 0.0
sectime = {}
farm_id_mapping = {}
#farm_deltas = defaultdict(lambda: {})
farm_metrics = {}
psTotal = 0
psdTotal = 0
remTotal = 0
allSummedplottingCount = 0
allSummedPlotting = 0
system_stats = {}
avgtime = defaultdict(lambda: {})
farm_names = []
disk_farms = set()
drive_directory = {}
farm_plot_size = defaultdict(lambda: "0")
replotting = defaultdict(lambda: False)
curr_sector_disk = defaultdict(lambda: 0)
sector_times = defaultdict(lambda: 0)
curr_farm = None
last_farm = int()
farmer_data = {}
curr_farm_name = "Default"
plot_space = {}
startTime = 0
deltas = defaultdict(lambda: '00:00')
remote_farms = {}
warnings = [str(), str(), str(), str(), str(), str(), str(),]
errors = [str(), str(), str(), str(), str(), str(), str(),]
last_logs = [str(), str(), str(), str(), str(), str(), str(),]
total_completed = 0
reward_count = 0
farm_rewards = defaultdict(lambda: int)
farm_recent_rewards = defaultdict(lambda: int)
farmer_name = 'WolfrageRocks'  # str()
ui_port = '8016'
event_times = defaultdict(str)
curr_line = str()
node_warnings = [str(), str(), str(), str(), str(), str(), str(),]
node_errors = [str(), str(), str(), str(), str(), str(), str(),]
total_error_count = 0
no_more_drives = False
wallet = str()
balance = "0.0"
peers = str()
best_block = str()
finalized = str()
imported = str()
ul = str()
dl = str()
node_log_file = str()
# However many initialized is how many it'll show
last_node_logs = [str(), str(), str(), str(), str(), str(),]
show_logging = True
hour_24 = False
name = str()
frame_delays = -1
latest_version = "Unknown"
toggle_encoding = False
toggle_encoding_node = False
running = False
farm_skips = defaultdict(int)
farm_recent_skips = defaultdict(int)
unroll = False
layout = None
rewards_per_hr = defaultdict(lambda: [])
tib_hr = 0
connected_farmer = False
live_drives = []
max_index = 0
